name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  flutter_tests:
    name: Run all flutter tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter doctor -v
      - run: flutter pub get
      - run: flutter clean
      - run: flutter test

  build_ios:
    name: Build Flutter app (iOS)
    needs: [flutter_tests]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter doctor -v
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios --no-codesign

  build_appbundle:
    name: Build Flutter app (Android)
    needs: [flutter_tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter doctor -v
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build appbundle
